messenger_cache:
    refresh_triggered_ttl: 600
    pools:
        default: filesystem
        runtime: runtime
        redis: redis
    decorated_message_buses:
        - cachedMessage.bus
    message_bus_decorators:
        '-1': PBaszak\MessengerCacheBundle\Tests\Helper\Domain\Decorator\LoggingMessageBusDecorator
