services:
    _defaults:
        autowire: true
        autoconfigure: true

    PBaszak\MessengerCacheBundle\:
        resource: '../../*'
        exclude:
            - '../../{Resources,DependencyInjection,MessengerCacheBundle.php}'

    messenger_cache.manager:
        class: PBaszak\MessengerCacheBundle\Manager\MessengerCacheManager

    PBaszak\MessengerCacheBundle\Contract\Replaceable\MessengerCacheManagerInterface:
        alias: messenger_cache.manager

    PBaszak\MessengerCacheBundle\Decorator\MessageBusCacheDecorator:
        arguments:
            - '@PBaszak\MessengerCacheBundle\Decorator\MessageBusCacheDecorator.inner'
            - '@messenger_cache.manager'

    PBaszak\MessengerCacheBundle\Handler\InvalidateAsyncHandler:
        tags: 
            - { name: 'messenger.message_handler', handles: PBaszak\MessengerCacheBundle\Message\InvalidateAsync }

    PBaszak\MessengerCacheBundle\Handler\RefreshAsyncHandler:
        tags: 
            - { name: 'messenger.message_handler', handles: PBaszak\MessengerCacheBundle\Message\RefreshAsync }
