framework:
    secret: '$ecretf0rt3st'
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    php_errors:
        log: true
    test: true
    http_method_override: false

services:
    _defaults:
        autowire: true
        autoconfigure: true

    PBaszak\MessengerCacheBundle\Tests\Helper\:
        resource: '../tests/Helper/*'
        exclude:
            - 'Kernel.php'

    Symfony\Component\Cache\Adapter\ArrayAdapter:
    Symfony\Component\Cache\Adapter\AdapterInterface:
        alias: Symfony\Component\Cache\Adapter\ArrayAdapter
    Symfony\Component\Cache\Adapter\PhpArrayAdapter:
        arguments:
            - '%kernel.cache_dir%/cache.php'
